CXXFLAGS += -std=c++11

clean:
	rm -f *.o *.a *.dylib a.out

# This is to verify that we find the transitive dependencies with the ldd approach
libbug.dylib: src/bug/trigger_bugs.cpp src/bug/trigger_bugs.h
	${CXX} ${CXXFLAGS} -dynamiclib -Wl,-headerpad_max_install_names -fpic -o libbug.dylib -install_name @executable_path/libbug.dylib $<

libexplore.dylib: src/explore/explore_me.cpp src/explore/explore_me.h libbug.dylib
	${CXX} ${CXXFLAGS} -dynamiclib -Wl,-headerpad_max_install_names -fpic -o libexplore.dylib -install_name @executable_path/libexplore.dylib -Isrc -L. -lbug $<

my_fuzz_test: libexplore.dylib
	@echo "Building $@"
	# The FUZZ_TEST_CXXFLAGS and FUZZ_TEST_LDFLAGS environment variables
	# are set by cifuzz when it executes the build command. Those must
	# be passed to the compiler and linker (compiling and linking is
	# done in a single invocation here, so we pass both to $CXX here).
	${CXX} ${CXXFLAGS} ${FUZZ_TEST_CXXFLAGS} ${FUZZ_TEST_LDFLAGS} -Wl,-search_paths_first -Wl,-headerpad_max_install_names -o $@ $@.cpp -L. -lexplore

crashing_fuzz_test.o: src/coverage/crashing_fuzz_test.cpp
	${CXX} ${CXXFLAGS} ${FUZZ_TEST_CXXFLAGS} -c $<

crashing_fuzz_test: crashing_fuzz_test.o
	${CXX} -o $@ crashing_fuzz_test.o ${LDFLAGS} ${FUZZ_TEST_LDFLAGS}
